DAOS-10595 build: Update DPDK to v21.11.1
Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

diff --git a/packaging/rpm_chrootbuild b/packaging/rpm_chrootbuild
--- a/packaging/rpm_chrootbuild
+++ b/packaging/rpm_chrootbuild
@@ -2,43 +2,9 @@
 
 set -uex
 
-# shellcheck disable=SC2153
-IFS=\| read -r -a distro_base_local_repos <<< "$DISTRO_BASE_LOCAL_REPOS"
-repo_adds=()
-repo_dels=()
-
-
-
-
-: "${DISTRO_NAME:=$DISTRO}"
-if [[ "${CHROOT_NAME}" = epel-8-* ]]; then
-    : "${DAOS_STACK_CENTOS_8_VERSION:=8}"
-    DISTRO_NAME="centos-${DAOS_STACK_CENTOS_8_VERSION}"
-elif [[ "${CHROOT_NAME}" = opensuse-leap-15* ]]; then
-    : "${DAOS_STACK_LEAP_15_VERSION:=15.3}"
-    DISTRO_NAME="opensuse-${DAOS_STACK_LEAP_15_VERSION}"
-fi
-: "${REPOSITORY_URL:=}"
-if [ -n "$REPOSITORY_URL" ] && [ -n "$DISTRO_REPOS" ]; then
-    repo_dels+=("--disablerepo=\*")
-elif [ "${CHROOT_NAME}" == "epel-8-x86_64" ]; then
-    # Special code to force building on CentOS 8.3
-    if [ "${DOT_VER}" -eq 3 ]; then
-        repo_dels+=("--disablerepo=\*")
-        repo_base='http://mirror.centos.org/centos/8.3.2011/'
-        distro_base_local_repos=(\
-"${repo_base}BaseOS/x86_64/os/" \
-"${repo_base}AppStream/x86_64/os/" \
-"${repo_base}extras/x86_64/os/" \
-"${repo_base}PowerTools/x86_64/os/" \
-https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/ )
-    fi
-fi
-
-: "${WORKSPACE:=$PWD}"
-mock_config_dir="$WORKSPACE/mock"
+mock_config_dir="${WORKSPACE:-$PWD}/mock"
 original_cfg_file="/etc/mock/${CHROOT_NAME}.cfg"
-cfg_file="$mock_config_dir/${CHROOT_NAME}_daos.cfg"
+cfg_file="$mock_config_dir/${CHROOT_NAME}.cfg"
 mkdir -p "$mock_config_dir"
 ln -sf /etc/mock/templates "$mock_config_dir/"
 ln -sf /etc/mock/logging.ini "$mock_config_dir/"
@@ -46,13 +12,43 @@ ln -sf /etc/mock/logging.ini "$mock_config_dir/"
 cp "$original_cfg_file" "$cfg_file"
 
 if [ "${CHROOT_NAME}" == "epel-8-x86_64" ]; then
-  echo -e "config_opts['module_enable'] = ['javapackages-tools:201801']" \
-       >> "$cfg_file"
-  if [ -n "${DOT_VER}" ]; then
-    echo -e "config_opts['macros']['%dist'] = '.el8_${DOT_VER}'" >> "$cfg_file"
-  fi
+    echo -e "config_opts['module_enable'] = ['javapackages-tools:201801']" \
+        >> "$cfg_file"
 fi
+
+# shellcheck disable=SC2153
+repo_adds=()
+repo_dels=()
+
 echo -e "config_opts['yum.conf'] += \"\"\"\n" >> "$cfg_file"
+
+if { [ -n "${REPOSITORY_URL:-}" ] || [ -n "${ARTIFACTORY_URL:-}" ]; } \
+   && [ -n "$DISTRO_REPOS" ]; then
+    repo_dels+=("--disablerepo=\*")
+
+    if [ -n "${REPO_FILE_URL:-}" ]; then
+        if [ -n "$REPO_FILES_PR" ]; then
+            if [[ $REPO_FILES_PR = PR-* ]]; then
+                build_number="lastSuccessfulBuild"
+                branch="$REPO_FILES_PR"
+                if [[ $branch = *:* ]]; then
+                    build_number="${branch#*:}"
+                    branch="${branch%:*}"
+                fi
+                REPO_FILE_URL="${JENKINS_URL:-https://build.hpdd.intel.com/}job/daos-do/job/repo-files/job/$branch/$build_number/artifact/"
+            else
+                if [ ! -d "$REPO_FILES_PR" ]; then
+                    echo "Could not find your specified directory \"$REPO_FILES_PR\" to read repo-files from"
+                    exit 1
+                fi
+                REPO_FILE_URL="file://$(readlink -e "$REPO_FILES_PR")/"
+            fi
+        fi
+        curl -sSf "$REPO_FILE_URL"daos_ci-"$DISTRO"-mock-artifactory.repo >> "$cfg_file"
+        repo_adds+=("--enablerepo *-artifactory")
+    fi
+fi
+
 for repo in $DISTRO_BASE_PR_REPOS $PR_REPOS; do
     branch="master"
     build_number="lastSuccessfulBuild"
@@ -67,11 +63,11 @@ for repo in $DISTRO_BASE_PR_REPOS $PR_REPOS; do
     repo_adds+=("--enablerepo $repo:$branch:$build_number")
     echo -e "[$repo:$branch:$build_number]\n\
 name=$repo:$branch:$build_number\n\
-baseurl=${JENKINS_URL:-https://build.hpdd.intel.com/}job/daos-stack/job/$repo/job/$branch/$build_number/artifact/artifacts/$DISTRO_NAME/\n\
+baseurl=${JENKINS_URL:-https://build.hpdd.intel.com/}job/daos-stack/job/$repo/job/$branch/$build_number/artifact/artifacts/$DISTRO/\n\
 enabled=1\n\
 gpgcheck=False\n" >> "$cfg_file"
 done
-for repo in $JOB_REPOS "${distro_base_local_repos[@]}"; do
+for repo in $JOB_REPOS; do
     repo_name=${repo##*://}
     repo_name=${repo_name//\//_}
     repo_adds+=("--enablerepo $repo_name")
@@ -83,9 +79,6 @@ done
 echo "\"\"\"" >> "$cfg_file"
 
 # shellcheck disable=SC2086
-eval mock --configdir "$mock_config_dir" -r "${CHROOT_NAME}_daos" \
-     "${repo_dels[*]}" "${repo_adds[*]}" \
+eval mock --configdir "$mock_config_dir" -r "${CHROOT_NAME}" \
+     ${repo_dels[*]} ${repo_adds[*]} --disablerepo=\*-debug* \
      $MOCK_OPTIONS $RPM_BUILD_OPTIONS "$TARGET"
-
-# For now just do an advisory check
-rpmlint "/var/lib/mock/${CHROOT_NAME}/result/"*.rpm || true
